### ISSUE TITLE
Allow third-party python extensions

### ISSUE THREAD

**Issue by RealA10N** [litemake/litemake#3]
Currently, litemake is a standalone Python CLI that helps you to compile your C/C++ project. When I started developing litemake I wanted it to become my main tool when working on C/C++ projects: such tool that will be able to run my tests, check my code syntax, and format it.

The idea is to allow other developers to "plug" into the litemake API and implement their own features in Python. Each target then will be able to specify which extension it would like to use.

The developer of the extension will be able to:
- Require new/different fields in the target
- Access collected files before and after compilation
- Modify the file collection process
- Print warning, errors, and regular output (through the litemake API)

For example, if I want to use the `litetest` extension for testing my code with a target named `test`, my `setup.litemake.toml` file will be similar to:

```toml
[litemake.meta]
name="hello-world"

[target.build]
sources=["src/**/*.cpp"]

[target.test]
sources=["tests/**/*.cpp"]
requires=["target:build"]
uses=["litetest"]
```
